# Course 1: Introduction Python

<center><img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" title="Python Logo"/></center>



This course covers the key Python skills you’ll need so you can start using Python for data science.

# 1.&nbsp;Understand&nbsp;your&nbsp;first&nbsp;Python&nbsp;program

In [ ]:
int_numberOfStudents = 0
print(int_numberOfStudents)

# Counting the number of students
int_numberOfStudents = int_numberOfStudents + 32

if int_numberOfStudents > 0:
    print("The class has started!")
text = "And the class will end one day!"
print(text)

0
The class has started!
And the class will end one day!


**Variable assignment:** Here `int_numberOfStudents` is called a **variable** and we **assign** it the value of 0 using `=`, which is called the assignment operator.
​
> **Aside**: If you've programmed in certain other languages (like Java or C++), you might be noticing some things Python *doesn't* require us to do here:  
- we don't need to "declare" `int_numberOfStudents` before assigning to it
- we don't need to tell Python what type of value `int_numberOfStudents` is going to refer to. In fact, we can even go on to reassign `int_numberOfStudents` to refer to a different sort of thing like a string or a boolean.

```
int_numberOfStudents = 0
```

**Variable assignment:** Here `int_numberOfStudents` is called a **variable** and we **assign** it the value of 0 using `=`, which is called the assignment operator.
​
> **Aside**: If you've programmed in certain other languages (like Java or C++), you might be noticing some things Python *doesn't* require us to do here:  
- we don't need to "declare" `int_numberOfStudents` before assigning to it
- we don't need to tell Python what type of value `int_numberOfStudents` is going to refer to. In fact, we can even go on to reassign `int_numberOfStudents` to refer to a different sort of thing like a string or a boolean.

```
print(int_numberOfStudents)
```
**Function calls:** `print` is a Python **function** that displays the value passed to it on the screen. We call functions by putting parentheses after their name, and putting the **inputs (or *arguments*)** to the function in those parentheses.

```
# Counting the number of students
```

**Comments:** The first line above is a comment. In Python, comments begin with the `#` symbol. Comments are ignored by the program, you can write whatever you want. We use comments to explain to others (and to ourselves) what we did when a part of the code is complex. 

It is very important to use comments and it is considered a basic of the **best practices** for **code readability**.

```
'''
These are multiline comments
Do not hesitate to use them
'''
```
Yes, you can also use multi-line comments like above
```
int_numberOfStudents = int_numberOfStudents + 4
```

**Reassignment:** Here we give the **variable** `int_numberOfStudents` a new value, we say that we are **reassigning** its value. Reassigning the value of an existing variable looks just the same as creating a variable - it still uses the `=` assignment operator.

In this case, the value we're assigning to `int_numberOfStudents` involves some simple arithmetic on its previous value. When it encounters this line, Python evaluates the expression on the right-hand-side of the `=` (0 + 4 = 4), and then assigns that value to the variable on the left-hand-side.

<center><img src="https://i.redd.it/zzxftm1ebwg71.jpg" width="400" height="400"></center>


```
if int_numberOfStudents > 0:
    print("The class has started!")
text = "And the class will end one day!"
print(text)
```

**Conditionals:** The keyword `ìf` is a **conditional**. We won't talk much about **conditionals** until later, but, even if you've never coded before, you can probably guess what this does. Python is prized for its readability and the simplicity.

Note how we indicated which code belongs to the if. "This code is in the if!" is only supposed to be printed if `int_numberOfStudents` is positive. But the later code (like `print("The class has started!")`)) should be executed no matter what. How do we (and Python) know that?

The colon (:) at the end of the if line indicates that a new code block is starting. Subsequent lines which are **indented** are part of that code block.

> **Aside**: If you've coded before, you might know that some other languages use {curly braces} to mark the beginning and end of code blocks. Python's use of meaningful whitespace can be surprising to programmers who are accustomed to other languages, but in practice it can lead to more consistent and readable code than languages that do not enforce indentation of code blocks.

Like comments, **indentation** is a **best practice** for **code readability** and in Python, it has become mandatory.

## Your turn 

A  **"Hello, World!"** program generally is a computer program that outputs or displays the message "Hello, World!". Such a program is very simple in most programming languages, and is often used to illustrate the basic syntax of a programming language. It is often the first program written by people learning to code. It can also be used as a sanity test to make sure that computer software intended to compile or run source code is correctly installed, and that the operator understands how to use it. 

 <font color='red'>**Exercize : Print "Hello, World!"**</font>

# 2.&nbsp;Standard&nbsp;variable&nbsp;types&nbsp;

In our first example we have seen two different **types of variables**. `int_numberOfStudents` is a numeric variable and `text` is a textual variable. In this chapter, we will see the most basic objects in Python.

## *2.1* Definitions

**Variables** are nothing but **reserved memory locations** to **store values**. This means that when you create a variable you reserve some space in memory.


Based on the data type of a variable, the interpreter allocates memory and decides what can be stored in the reserved memory. Therefore, by assigning different data types to variables, you can store integers, decimals or characters in these variables.

<center><img src="https://www.researchgate.net/profile/Prabhudev-Irabashetti/publication/265166374/figure/fig1/AS:295882936340490@1447555397972/Memory-Allocation-Problem.png" width="600" height="400"></center>

**Object and Class** : an **object** is simply a **collection of data (variables) and methods (functions)** that act on those data. A **class** is a **blueprint** for an object.

We can think of a class as a sketch (prototype) of a house. It contains all the details about the floors, doors, windows, etc. Based on these descriptions we build the house. House is the object.

As many houses can be made from a house's blueprint, we can create many objects from a class. An object is also called an instance of a class and the process of creating this object is called instantiation.

<center><img src="https://electricalworkbook.com/wp-content/uploads/2018/09/python_class-1024x700.png" width="600" height="400"></center>

**Functions** : a **function** is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result.

**Methods** 
Python method is like a function, except it is attached to an object. We call a method on an object, and it possibly makes changes to that object. A method, then, belongs to a class. Let’s take an example.


<center><img src="https://techvidvan.com/tutorials/wp-content/uploads/sites/2/2020/04/python-methods-vs-functions.jpg" width="600" height="400"></center>


## *2.2* Basic types of variables

The data stored in memory can be of many types. For example, a person's age is stored as a numeric value and his or her address is stored as alphanumeric characters. Python has various standard data types that are used to define the operations possible on them and the storage method for each of them.

Python has five standard data types :

*   `Number`
*   `String` 
*   `List` 
*   `Tuple`
*   `Dictionary`


    
    
    
    
    


### *2.2.1* Numbers and arithmetic in Python

`Number` is a fine informal name for the kind of thing, but if we wanted to be more technical, we could ask Python how it would describe the type of thing that int_numberOfStudents is:


In [ ]:
int_numberOfStudents = 4
type(int_numberOfStudents)



It's an `int` - short for **integer**. There's another sort of number we commonly encounter in Python:


In [ ]:
type(19.95)

A `float` is a **number with a decimal place** - very useful for representing things like weights or proportions.

`type()` is the second built-in function we've seen (after print()), and it's another good one to remember. It's very useful to be able to ask Python "what kind of thing is this?".




> **Aside**: Python supports four different numerical types :
* `int` (signed integers)
* `long` (long integers, they can also be represented in octal and hexadecimal)
* `float` (floating point real values)
* `complex` (complex numbers)

A natural thing to want to do with numbers is perform arithmetic. We've seen the `+` operator for addition, and the `*` operator for multiplication. Python also has us covered for the rest of the basic buttons on your calculator:

| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Addition       | Sum of ``a`` and ``b``                                 |
| ``a - b``    | Subtraction    | Difference of ``a`` and ``b``                          |
| ``a * b``    | Multiplication | Product of ``a`` and ``b``                             |
| ``a / b``    | True division  | Quotient of ``a`` and ``b``                            |
| ``a // b``   | Floor division | Quotient of ``a`` and ``b``, removing fractional parts |
| ``a % b``    | Modulus        | Integer remainder after division of ``a`` by ``b``     |
| ``a ** b``   | Exponentiation | ``a`` raised to the power of ``b``                     |
| ``-a``       | Negation       | The negative of ``a``                                  |


Exercize : fill in the table 

| a      | Operation | b   | Result | Type |
|--------|-----------|-----|--------|------|
| 1      | +         | 1   | ?      | ?    | 
| 1.0    | +         | 1   | ?      | ?    | 
| 1      | +         | 0.0 | ?      | ?    | 
| 1      | -         | 1   | ?      | ?    | 
| 1      | -         | 0   | ?      | ?    | 
| 1      | -         | 0.0 | ?      | ?    | 
| 1      | -         | 1.0 | ?      | ?    | 
| 1      | *         | 1   | ?      | ?    | 
| 1.0    | *         | 1   | ?      | ?    | 
| 1      | *         | 0.0 | ?      | ?    | 
| 1      | /         | 1   | ?      | ?    | 
| 0      | /         | 1   | ?      | ?    |
| 1      | /         | 0   | ?      | ?    |
| 3      | /         | 2   | ?      | ?    |
| 123456 | /         | 3   | ?      | ?    |
| 1      | //        | 1   | ?      | ?    |
| 0      | //        | 1   | ?      | ?    |
| 1      | //        | 0   | ?      | ?    |
| 3      | //        | 2   | ?      | ?    |
| 123456 | //        | 3   | ?      | ?    |
| 1      | %         | 1   | ?      | ?    |
| 9      | %         | 3   | ?      | ?    |
| 8      | %         | 3   | ?      | ?    |
| 7      | %         | 3   | ?      | ?    |
| 0      | %         | 1   | ?      | ?    |
| 1      | %         | 0   | ?      | ?    |

### *2.2.2* Strings

Strings in Python are identified as a **contiguous set of characters** represented in the quotation marks. Python allows for either pairs of single `'` or double quotes`"`.

Double quotes are convenient if your string contains a single quote character (e.g. representing an apostrophe).

```
print("Pluto's a planet!")
```

Similarly, it's easy to create a string that contains double-quotes if you wrap it in single quotes:

```
print('My dog is named "Pluto"')
```

In addition, Python's triple quote syntax for strings lets us include newlines literally (i.e. by just hitting 'Enter' on our keyboard, rather than using the special '\n' sequence). We've already seen this in the docstrings we use to document our functions, but we can use them anywhere we want to define a string.

```
triplequoted_hello = """hello
world"""
```


The plus sign `+` is the string concatenation operator and the asterisk `*` is the repetition operator.

<table>
    <thead>
        <tr>
            <th>a</th>
            <th>operation</th>
            <th>b</th>
            <th>result</th>
            <th>type</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>"This is"</td>
            <td>+</td>
            <td>"EM"</td>
            <td>?</td>
            <td>?</td>
        </tr>
        <tr>
            <td>"I am "</td>
            <td>+</td>
            <td>3</td>
            <td>?</td>
            <td>?</td>
        </tr>
        <tr>
            <td>"I am "</td>
            <td>*</td>
            <td>3</td>
            <td>?</td>
            <td>?</td>
        </tr>
        <tr>
            <td>"Spiderman"</td>
            <td>==</td>
            <td>"Spiderman"</td>
            <td>?</td>
            <td>?</td>
        </tr>
        <tr>
            <td>"a"</td>
            <td><</td>
            <td>"b"</td>
            <td>?</td>
            <td>?</td>
        </tr>
        <tr>
            <td>"a"</td>
            <td>></td>
            <td>"b"</td>
            <td>?</td>
            <td>?</td>
        </tr>
    </tbody>
</table> 


#### Indexing

You can access individual characters of a `string` with square brackets.

Which is the first letter? Python uses <em>zero-based</em> indexing, so the first element has index 0.

In [ ]:
poem = "Roses are red, violets are blue"

Elements at the end of the string can be accessed with negative numbers, starting from -1

Try these operations:

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>poem[0]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[2]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[-1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[-2]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[1] = "A"</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

As you can see, strings are **immutable**, meaning we can't modify them. 

#### Slicing

Strings can be thought of as sequences of characters. 
What are the first three characters? We can answer this question using slicing:

```
poem[0:3]
```

Try these :
<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>poem[0:3]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[:3]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[1:2]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[1:-1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem[-2:]</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

#### String functions

Python has several useful functions for working with strings.

`len` gives the length of a string:

In [ ]:
# How many characters are there?
len(poem)

31

```sorted```returns a sorted version of a string:

In [ ]:
sorted(poem)

```max``` and ```min``` return the biggest and the smallest character.
Try : 

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>max(poem)</td>
            <td>?</td>
        </tr>
        <tr>
            <td>min(poem)</td>
            <td>?</td>
        </tr>
    </tbody>
</table>


#### Methods

The type `str` has lots of very useful **methods**. I'll show just a few examples here.

`str.lower()` returns all the characters in lower case

`str.upper()` returns all the characters in upper case

`str.index("stuff")` returns the index (position) of the string you entered if it exists in the string

`str.startswith("stuff")` returns True if the string starts with the string given in input, else False

`str.endswith("stuff")` returns True if the string ends with the string given in input, else False

`str.split("stuff")` split the string in a list of strings, separated on the string given in input

`str.strip()` removes the space at the begining and at the end of the string

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>poem.lower()</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.upper()</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.index("violet")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.index("vioet")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.startswith("violet")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.startswith("Roses")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.startswith("roses")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.endswith("blue")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.split()</td>
            <td>?</td>
        </tr>
        <tr>
            <td>poem.split(",")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>" Hello ".strip()</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

In [ ]:
poem.split(",")

['Roses are red', ' violets are blue']

### *2.2.3* List

#### Create a list

Lists in Python represent ordered sequences of values. Here is an example of how to create them:

In [ ]:
ages = [2, 3, 5, 7]
students = ["Lucas", "Sara", "Pierre", "Olivier"]
choices = [True, True, False, True]

We can put many types in a list. We can even make a list of lists : 

In [ ]:
profiles = [[2, "Lucas", True], [3, "Sara", True], [5, "Pierre", False]]

And as you can see, a list can contain a mix of different types of variables. It's not true (or as easy) for every languages, so be careful

Try : 
```
profiles * 2
```
What happens ? 
```
???
```


Try : 
```
profiles + ["a"]
```
What happens ? 
```
???
```


#### Indexing

You can access individual list elements with square brackets.

Which `student` is the first of the list? 

Python uses <em>zero-based</em> indexing, so the first element has index 0.

Elements at the end of the list can be accessed with negative numbers, starting from -1

Try these operations:

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>students[0]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students[1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students[-1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students[-2]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students[-3]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>profiles[1]</td>
            <td>?</td>
        </tr>
    </tbody>
</table>



Now, how do you get the value ```"Sara"``` from the list ```profiles``` ? 

Write it below to remember :
```
???
```

#### Slicing

What are the first three students? We can answer this question using slicing:

```
students[0:3]
```

Try these operations:

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>students[0:3]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students[-2:]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>profiles[:3]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>profiles[1:1]</td>
            <td>?</td>
        </tr>
        <tr>
            <td>profiles[-2:]</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

#### List functions

Python has several useful functions for working with lists.

`len` gives the length of a list:

In [ ]:
# How many students are there?
len(students)

4

`sorted`returns a sorted version of a list:

In [ ]:
sorted(students)

['Lucas', 'Olivier', 'Pierre', 'Sara']

In [ ]:

sorted(choices)

[False, True, True, True]

```sum``` and ```max``` and ```min``` do what you might expect.
Try : 


<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
            <th>Formule</th>
            <th>Result</th>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>sum(ages)</td>
            <td>?</td>
            <td>max(ages)</td>
            <td>?</td>
            <td>min(ages)</td>
            <td>?</td>
        </tr>
        <tr>
            <td>sum(students)</td>
            <td>?</td>
            <td>max(students)</td>
            <td>?</td>
            <td>min(students)</td>
            <td>?</td>
        </tr>
        <tr>
            <td>sum(choices)</td>
            <td>?</td>
            <td>max(choices)</td>
            <td>?</td>
            <td>min(choices)</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

#### List methods

The type `list` has lots of very useful **methods**. I'll show just a few examples here.

`list.append(element)` adds an element to the list

`list.pop()` removes the last element of a list and return it

`list.index(element)` return the index (position) of the element in the list, if it exists else, it will return an error

To avoid unpleasant surprises like this, we can use the `in` operator to determine whether a list contains a particular value.

```
element in list -> return True or False
```



Now try : 

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>students.append("Maurice")</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students.append(1)</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students.pop()</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students.index(1)</td>
            <td>?</td>
        </tr>
        <tr>
            <td>students.index("Lucas")</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

### *2.2.4* Tuples

A **tuple** is a collection of Python objects separated by commas. In someways a tuple is similar to a list in terms of indexing, nested objects and repetition but a tuple is **immutable** unlike lists which are mutable.


In [ ]:
tup = ('python', 'is awesome')
print(tup)
print(type(tup))

('python', 'is awesome')
<class 'tuple'>


### *2.2.5* Dictionnaries

#### Create a dictionnary 

**Dictionnaries** are a built-in Python data structure for mapping **keys to values**.

In [ ]:
dictionnary = {'key1':"value1", 'key2':"value2", 3:300}

In this case 'key1', 'key2', and 3 are the keys, and "value1", "value2" and 300 are their corresponding values.

Values are accessed via square bracket syntax similar to indexing into lists and strings.

In [ ]:
dictionnary['key1']

'value1'

We can use the same syntax to add another key, value pair

In [ ]:
dictionnary['eleven'] = 11

Or to change the value associated with an existing key

In [ ]:
dictionnary['key1'] = 1

The `in` operator tells us whether something is a key in the dictionary

In [ ]:
'key1' in dictionnary

True

#### Methods

The type `dict` has lots of very useful **methods**. I'll show just a few examples here.

`dict.keys()` returns a list containing all the elements of the dictionnary

`dict.values()` returns a list containing all the values of the dictionnary

Now try : 

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>dictionnary.keys()</td>
            <td>?</td>
        </tr>
        <tr>
            <td>dictionnary.values()</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

### *2.2.6* Summary

There are many other objects that you will discover with time. 

Here is a small summary of what we have seen and other basic objects : 


<center><img src="https://miro.medium.com/max/1200/1*QfI8H_8HplGa1v9IrrWjBA.png" width="800" height="400"></center>



# 3. Logic and Conditions

## *3.1* Booleans

Python has a type of variable called `bool`. It has two possible values: `True` or `False`.

In [ ]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


Rather than putting ```True``` or ```False``` directly in our code, we usually get boolean values from **boolean operators**. These are operators that answer yes/no questions. We'll go through some of these operators below.

| Operation | Description | | Operation | Description |
| ------ | ------ |-| ------ | ------ |
|a == b |	a equal to b 	| |	a != b |	a not equal to b |
|a < b |	a less than b | |	a > b |	a greater than b |
|a <= b |	a less than or equal to b | |	a >= b | a greater than or equal to b|

Try these operations :

| Operator And | Result | | Operator Or | Result | | Operator Not | Result |
| ------ | ------ |-| ------ | ------ |-| ------ | ------ |
|True and True | ?	| |	True or True | ? | | Not True | ? |
|True and False |	? | |	True or False |	? | | Not False | ? |
|False and True |	? | |	False or True |	? |
|False and False | ?	| |	False or False | ? |

Booleans are considered a numeric type in Python. This means they’re numbers for all intents and purposes. In other words, you can apply arithmetic operations to Booleans, and you can also compare them to numbers.

There aren’t many uses for the numerical nature of Boolean values, but there’s one technique you may find helpful. Because `True` is equal to `1` and `False` is equal to `0`, adding Booleans together is a quick way to count the number of `True` values. This can come in handy when you need to count the number of items that satisfy a condition.

Now try these :

| Bool == Int | Result | | Bool and Int | Result | | Bool == String | Result | | With Floats | Result |
| ------ | ------ |-| ------ | ------ |-| ------ | ------ |-| ------ | ------ |
|True == 1 | ? | | True and 1 |	? | | True == '1' | ? | | True == 1.0 | ? |
|False == 0 | ? | | True and 0 | ? | | False == '1' | ? | | 1 == 1.0 | ? |
|True == 0 | ? | | False and 1 | ? | | False == '0' | ? |
|False == 1 | ? | | False and 0 | ? |









As you can see, ```True``` is equivalent to ```1``` and equivalent to ```1.0``` but not to ```'1'```. 

<font color='red'>**So be very careful when you compare values of different types.**</font>




If `True` is like `1` and `False` is like `0`, then  the operator `and` is like a multiplication and the operator `or` is like an addition and we look if the result is superior to zero.

Ex 1:

```
True and False ( == False)
1 * 0 ( == 0  so it's False)
```

Ex 2:

```
True or True ( == True)
1 + 1 ( == 2 > 0 so it's True)
```





## *3.2* Conditions : if, elif, else (si, alors si, sinon)

Booleans are most useful when combined with conditional statements, using the keywords ```if```, ```elif```, and ```else```.

Conditional statements, often referred to as <em>if-then</em> statements, let you control what pieces of code are run based on the value of some Boolean condition. Here's an example:

In [ ]:
x = 2

if (x == 0):
    print(x, "is zero")
elif (x > 0):
    print(x, "is positive")
elif (x < 0):
    print(x, "is negative")
else:
    print(x, "is unlike anything I've ever seen...")

print("I am out of the condition")

2 is positive
I am out of the condition


The ```if``` and ```else``` keywords are often used in other languages; its more unique keyword is ```elif```, a contraction of "else if". In these conditional clauses, ```elif``` and ```else``` blocks are optional; additionally, you can include as many ```elif``` statements as you would like.

Note especially the use of colons (```:```) and whitespace to denote separate blocks of code. This is similar to what happens when we define a function - the function header ends with ```:```, and the following line is indented with 4 spaces. All subsequent indented lines belong to the body of the function, until we encounter an unindented line, ending the function definition.

# 4. Loop

## *4.1* For loops

Loops are a way to repeatedly execute some code. Here's an example:

In [ ]:
for number in [1,2,3,4,5]:
    print(number)

1
2
3
4
5


The ```for``` loop specifies


*   the variable name to use (in this case, number)
*   the set of values to loop over (in this case, [1,2,3,4,5])


You use the word `in` to link them together.

The object to the right of the `in` can be any object that supports iteration. Basically, if it can be thought of as a group of things, you can probably loop over it. In addition to lists, we can iterate over the elements of a tuple:

In [ ]:
multiplicands = (2, 2, 2, 3, 3, 5)
product = 1
for mult in multiplicands:
    product = product * mult
product

360

You can even loop through each character in a string:

In [ ]:
s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''
# print all the uppercase letters in s, one at a time
for char in s:
    if char.isupper():
        print(char, end='')   

HELLO

**range()**

`range()` is a function that returns a sequence of numbers. It turns out to be very useful for writing loops.

For example, if we want to repeat some action 5 times:

In [ ]:
for i in range(5):
    print("Doing important work. i =", i)

Doing important work. i = 0
Doing important work. i = 1
Doing important work. i = 2
Doing important work. i = 3
Doing important work. i = 4


## *4.2* While loops

The other type of loop in Python is a `while` loop, which iterates until some condition is met:

```
i = 0
while i < 10:
    print(i, end=' ')
    i += 1 # increase the value of i by 1
```
The argument of the while loop is evaluated as a boolean statement, and the loop is executed **until the statement evaluates to False**.

<font color='red'>**Warning : while loops can lead to infinite loop quite easily.**</font> Here, if we did not assign ```i = i + 1```, we would loop forever, waiting for `i` to be equal to 10.


## List comprehension

List comprehensions are one of Python's most beloved and unique features. The easiest way to understand them is probably to just look at a few examples:

In [ ]:
squares = [n**2 for n in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Here's how we would do the same thing without a list comprehension:

In [ ]:
squares = []
for n in range(10):
    squares.append(n**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

We can also add an if condition:

In [ ]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
short_planets = [planet for planet in planets if len(planet) < 6]
short_planets

['Venus', 'Earth', 'Mars']

Here's an example of filtering with an `if` condition and applying some transformation to the loop variable:


In [ ]:
# str.upper() returns an all-caps version of a string
loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6]
loud_short_planets

['VENUS!', 'EARTH!', 'MARS!']

The expression on the left doesn't technically have to involve the loop variable (though it'd be pretty unusual for it not to). What do you think the expression below will evaluate to? Press the 'output' button to check.

In [ ]:
[32 for planet in planets]

[32, 32, 32, 32, 32, 32, 32, 32]

# 5. Functions

## *5.1* Defining functions

Built-in functions are great, but we can only get so far with them before we need to start defining our own functions. Below is a simple example.


In [ ]:
def least_difference(a, b, c):
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

This creates a function called `least_difference`, which takes three arguments, `a`, `b`, and `c`.

Functions start with a header introduced by the `def` keyword. The indented block of code following the `:` is run when the function is called.

`return` is another keyword uniquely associated with functions. When Python encounters a return statement, it exits the function immediately, and passes the value on the right hand side to the calling context.

Is it clear what `least_difference()` does from the source code? If we're not sure, we can always try it out on a few examples:


In [ ]:
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7), # Python allows trailing commas in argument lists. How nice is that?
)

9 0 1


## *5.2* Functions that don't return 

What would happen if we didn't include the `return` keyword in our function?

In [ ]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    min(diff1, diff2, diff3)
    
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7),
)

None None None


Python allows us to define such functions. The result of calling them is the special value `None`. (This is similar to the concept of "null" in other languages.)

Without a `return` statement, least_difference is completely pointless, but a function with side effects may do something useful without returning anything. We've already seen one example of this: `print()` doesn't return anything. We only call it for its side effect (putting some text on the screen). Other examples of useful side effects include writing to a file, or modifying an input.


## *5.3* Default arguments

When we called `print(a)`, we saw that the `print` function has several optional arguments. For example, we can specify a value for `sep` to put some special string in between our printed arguments:

In [ ]:
print(1, 2, 3, sep=' < ')

1 < 2 < 3


But if we don't specify a value, `sep` is treated as having a default value of `' '` (a single space).

In [ ]:
print(1, 2, 3)

1 2 3


Adding optional arguments with default values to the functions we define turns out to be pretty easy:

In [ ]:
def greet(who="Colin"):
    print("Hello,", who)
    
greet()
greet(who="EM")
# (In this case, we don't need to specify the name of the argument, because it's unambiguous.)
greet("world")

Hello, Colin
Hello, EM
Hello, world


## *5.4* Functions applied to functions (bonus)

Here's something that's powerful, though it can feel very abstract at first. You can supply functions as arguments to other functions. Some example may make this clearer:

In [ ]:
def mult_by_five(x):
    return 5 * x

def call(fn, arg):
    """Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1), 
    sep='\n', # '\n' is the newline character - it starts a new line
)

5
25


Functions that operate on other functions are called "higher-order functions." You probably won't write your own for a little while. But there are higher-order functions built into Python that you might find useful to call.

Here's an interesting example using the `max` function.

By default, `max` returns the largest of its arguments. But if we pass in a function using the optional `key` argument, it returns the argument `x` that maximizes `key(x)` (aka the 'argmax').


In [ ]:
def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5

print(
    'Which number is biggest?',
    max(100, 51, 14),
    'Which number is the biggest modulo 5?',
    max(100, 51, 14, key=mod_5),
    sep='\n',
)

Which number is biggest?
100
Which number is the biggest modulo 5?
14


# Your turn

## *1.3* Create my first script in Python

<font color='red'>**Exercize :** </font>
Reproduce the function `sum(list)`, without any built-in functions, on list of integers, floats. With a `for` loop. 



<font color='red'>**Exercize :** </font>
Reproduce the function `sum(list)`, without any built-in functions, on list of integers, floats. With a `while` loop. 

<font color='red'>**Exercize :** </font>
Reproduce the function `max(list)`, without any built-in functions, on list of integers, floats and strings. 

**Hint** : You can do it by using a `for` loop and an `if`.

<font color='red'>**Exercize :** </font>
Reproduce the function `list.index(element)`, without any built-in functions, on list of integers, floats and strings. 

**Hint** : You can do it by using a `for` loop and an `if`.

<font color='red'>**Exercize :** </font>
Reproduce the function `sorted(list)`, without any built-in functions, on list of integers, floats and strings. 

**Hint** : You can do it by using a `for` loop and an `if`, 2 lists where one is empty and will be completed steps by steps

<font color='red'>**Exercize :** </font>
Create a list of the `n` first prime numbers, you can use any built-in function but you need to create a function that will take n as a parameter and return the list


# *3*. Python objects commonly used in Data Analysis

## *3.1* Numpy Matrix

`NumPy` is a fundamental library that most of the widely used Python data processing libraries are built upon (`pandas`, `OpenCV`), inspired by (`PyTorch`), or can efficiently share data with (`TensorFlow`, `Keras`, etc). Understanding how `NumPy` works gives a boost to your skills in those libraries as well. It is also…

The central concept of `NumPy` is an n-dimensional array. The beauty of it is that most operations look just the same, no matter how many dimensions an array has. But 1D and 2D cases are a bit special.

### *3.1.0* Using NumPy

To use the NumPy arrays, we need to import the numpy package

In [ ]:
import numpy as np

### *3.1.1* Creating 1D Arrays

We can create a NumPy array (a.k.a. the mighty ndarray) by passing a python list to it and using ` np.array()`. In this case, python creates the array we can see on the right here:

In [ ]:
data = np.array([1,2,3])
print(data)

[1 2 3]
[1. 1. 1.]


<center><img src="http://jalammar.github.io/images/numpy/create-numpy-array-1.png" width="600" height="200"></center>

There are often cases when we want NumPy to initialize the values of the array for us. NumPy provides methods like ones(), zeros(), and random.random() for these cases. We just pass them the number of elements we want it to generate:

<center><img src="http://jalammar.github.io/images/numpy/create-numpy-array-ones-zeros-random.png" width="800" height="200"></center>


In [ ]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


### *3.1.2* Array Arithmetic

Adding numpy arrays position-wise (i.e. adding the values of each row) is as simple as typing `data` + `ones`:

In [ ]:
data + ones

array([2., 3., 4.])

Position wise operation is a wonderful abstraction that allows you to think about problems at a higher level.

And it’s not only addition that we can do this way:

<center><img src="http://jalammar.github.io/images/numpy/numpy-array-subtract-multiply-divide.png" width="800" height="100"></center>

There are often cases when we want to carry out an operation between an array and a single number (we can also call this an operation between a vector and a scalar). Say, for example, our array represents distance in miles, and we want to convert it to kilometers. We simply say  : 


In [ ]:
data * 1.6

array([1.6, 3.2, 4.8])


<center><img src="http://jalammar.github.io/images/numpy/numpy-array-broadcast.png" width="800" height="100"></center>

See how NumPy understood that operation to mean that the multiplication should happen with each cell? That concept is called **broadcasting**, and it’s very useful.

### *3.1.3* Indexing

We can index and slice NumPy arrays in all the ways we can slice python lists:

<center><img src="http://jalammar.github.io/images/numpy/numpy-array-slice.png" width="800" height="200"></center>

### *3.1.4* Aggregation

Additional benefits NumPy gives us are aggregation functions:

<center><img src="http://jalammar.github.io/images/numpy/numpy-array-aggregation.png" width="800" height="150"></center>

In addition to `min`, `max`, and `sum`, you get all the greats like `mean` to get the average, `prod` to get the result of multiplying all the elements together, `std` to get standard deviation, and plenty of others.

### *3.1.5* Creating nD Arrays

In [ ]:
arr_2D0 = np.array([[1,2],[3,4]])
arr_2D1 = np.array([[1,2, 3],[4, 5, 6], [7,8,9]])
arr_2D2 = np.array([[1,2, 3],[4, 5, 6], [7,8,9], [10,11,12]])
arr_3D = np.array([[[1,2, 3],[4, 5, 6]], [[7,8,9], [10,11,12]]])
print(arr_2D0, arr_2D1, arr_2D2, arr_3D, sep="\n ___ \n")

[[1 2]
 [3 4]]
 ___ 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 ___ 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 ___ 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


<center><img src="http://jalammar.github.io/images/numpy/numpy-array-create-2d.png" width="500" height="100"></center>

<center><img src="http://jalammar.github.io/images/numpy/numpy-3d-array.png" width="500" height="200"></center>

We can also use the same methods we mentioned above (`ones()`, `zeros()`, and `random.random()`) as long as we give them a tuple describing the dimensions of the matrix we are creating:

<center><img src="http://jalammar.github.io/images/numpy/numpy-matrix-ones-zeros-random.png" width="800" height="150"></center>

<center><img src="http://jalammar.github.io/images/numpy/numpy-3d-array-creation.png" width="800" height="200"></center>

### *3.1.6* nD Arithmetic

We can add and multiply matrices using arithmetic operators (`+-*/`) if the two matrices are the same size. NumPy handles those as position-wise operations:

<center><img src="http://jalammar.github.io/images/numpy/numpy-matrix-arithmetic.png" width="700" height="150"></center>

We can get away with doing these arithmetic operations on matrices of different size only if the different dimension is one (e.g. the matrix has only one column or one row), in which case NumPy uses its broadcast rules for that operation:

<center><img src="http://jalammar.github.io/images/numpy/numpy-matrix-broadcast.png" width="800" height="150"></center>

Try these :

<table>
    <thead>
        <tr>
            <th>Formule</th>
            <th>Result</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>arr_2D0 + 1</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D1 + 1</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D2 + 1</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D0 + np.array([1, 1])</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D0 + np.array([1], [1])</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D2 + np.array([1,1,1])</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D2 + np.array([1,1,1,1])</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_2D2 + np.array([[1],[1],[1],[1]])</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_3D + 1</td>
            <td>?</td>
        </tr>
        <tr>
            <td>arr_3D + np.array([[1,0,1], [0,1,0]])</td>
            <td>?</td>
        </tr>
    </tbody>
</table>

In [ ]:
arr_3D + np.array([[1,0,1], [0,1,0]])

array([[[ 2,  2,  4],
        [ 4,  6,  6]],

       [[ 8,  8, 10],
        [10, 12, 12]]])

### *3.1.7* Your turn


<font color='red'>**Exercize :** </font>
For 1D and 2D numpy arrays, create a function where you give 2 arrays with the same dimensions as inputs, and you return a list containing the positions where the arrays have identical elements.If the numpy arrays are 1D, you will return a list of index. If the numpy arrays are 2D, it will return a list of tuples where the elements are the positions.

### *3.1.8* Data Representation

If you are wondering why we are playing with numpy arrays, you will see here what they can be used for.
Think of all the data types you’ll need to crunch and build models around (spreadsheets, images, audio…etc). So many of them are perfectly suited for representation in an n-dimensional array:

**Tables and Spreadsheets** 

A spreadsheet or a table of values is a two dimensional matrix. Each sheet in a spreadsheet can be its own variable. The most popular abstraction in python for those is the pandas dataframe, which actually uses NumPy and builds on top of it.

<center><img src="http://jalammar.github.io/images/pandas-intro/0%20excel-to-pandas.png" width="800" height="300"></center>

**Audio and Timeseries** 

An audio file is a one-dimensional array of samples. Each sample is a number representing a tiny chunk of the audio signal. CD-quality audio may have 44,100 samples per second and each sample is an integer between -32767 and 32768. Meaning if you have a ten-seconds WAVE file of CD-quality, you can load it in a NumPy array with length 10 * 44,100 = 441,000 samples. Want to extract the first second of audio? simply load the file into a NumPy array that we’ll call audio, and get audio[:44100].

<center><img src="http://jalammar.github.io/images/numpy/numpy-audio.png" width="800" height="250"></center>

The same goes for time-series data (for example, the price of a stock over time).

**Images**

An image is a matrix of pixels of size (height x width).

If the image is black and white (a.k.a. grayscale), each pixel can be represented by a single number (commonly between 0 (black) and 255 (white)). Want to crop the top left 10 x 10 pixel part of the image? Just tell NumPy to get you image[:10,:10].

Here’s a look at a slice of an image file:

<center><img src="http://jalammar.github.io/images/numpy/numpy-grayscale-image.png" width="800" height="300"></center>

If the image is colored, then each pixel is represented by three numbers - a value for each of red, green, and blue. In that case we need a 3rd dimension (because each cell can only contain one number). So a colored image is represented by an ndarray of dimensions: (height x width x 3).

<center><img src="http://jalammar.github.io/images/numpy/numpy-color-image.png" width="800" height="350"></center>

## *3.2* Pandas

You'll learn all about `pandas`, the most popular Python library for data analysis.

In this tutorial, you will learn how to create your own data, and on the next class, you will work on real data.

### *3.2.0* Using pandas

To use pandas, you'll typically start with the following line of code.

In [ ]:
import pandas as pd

### *3.2.1* Creating a pandas DataFrame

There are two core objects in pandas: the `DataFrame` and the `Series`.
DataFrame

A `DataFrame` is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

For example, consider the following simple `DataFrame`:

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

Yes   No
0   50  131
1   21    2

In this example, the "0, No" entry has the value of 131. The "0, Yes" entry has a value of 50, and so on.

`DataFrame` entries are not limited to integers. For instance, here's a `DataFrame` whose values are strings:


In [ ]:
df_bobAndSueAndBot = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.', 'Meh'], 'Sue': ['Pretty good.', 'Bland.', 'Overated'], 'Bot': [1, 0, 0.5]})
df_bobAndSueAndBot

Bob           Sue  Bot
0    I liked it.  Pretty good.  1.0
1  It was awful.        Bland.  0.0
2            Meh      Overated  0.5

We are using the `pd.DataFrame()` constructor to generate these DataFrame objects. The syntax for declaring a new one is a dictionary whose keys are the column names (Bob and Sue in this example), and whose values are a list of entries. This is the standard way of constructing a new DataFrame, and the one you are most likely to encounter.

The dictionary-list constructor assigns values to the column labels, but just uses an ascending count from 0 (0, 1, 2, 3, ...) for the row labels. Sometimes this is OK, but oftentimes we will want to assign these labels ourselves.

The list of row labels used in a DataFrame is known as an `Index`. We can assign values to it by using an `index` parameter in our constructor:


In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.', 'Meh'], 
              'Sue': ['Pretty good.', 'Bland.', 'Overated']},
             index=['Product A', 'Product B'])

Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

### *3.2.2* Creating a pandas Serie

A `Series`, by contrast, is a sequence of data values. If a `DataFrame` is a table, a `Series` is a list. And in fact you can create one with nothing more than a list:

In [ ]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A `Series` is, in essence, a single column of a `DataFrame`. So you can assign column values to the `Series` the same way as before, using an index parameter. However, a Series does not have a column name, it only has one overall name:

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

The `Series` and the `DataFrame` are intimately related. It's helpful to think of a `DataFrame` as actually being just a bunch of `Series` "glued together". We'll see more of this in the next section of this tutorial.

### *3.3.3* Accessing a DataFrame column

In Python, we can access the property of an object by accessing it as an attribute. A `book` object, for example, might have a `title` property, which we can access by calling `book.title`. Columns in a pandas DataFrame work in much the same way.

Hence to access the `Bob` property of `df_bobAndSueAndBot` we can use:


In [ ]:
df_bobAndSueAndBot.Bob

0      I liked it.
1    It was awful.
Name: Bob, dtype: object

If we have a Python dictionary, we can access its values using the indexing ([]) operator. We can do the same with columns in a DataFrame:

In [ ]:
df_bobAndSueAndBot['Bob']

0      I liked it.
1    It was awful.
Name: Bob, dtype: object

These are the two ways of selecting a specific Series out of a DataFrame. Neither of them is more or less syntactically valid than the other, but the indexing operator `[]` does have the advantage that it can handle `column` names with reserved characters in them (e.g. if we had a `country providence` column, `reviews.country providence` wouldn't work).

Doesn't a pandas Series look kind of like a fancy dictionary? It pretty much is, so it's no surprise that, to drill down to a single specific value, we need only use the indexing operator `[]` once more:


In [ ]:
df_bobAndSueAndBot['Bob'][0]

'I liked it.'

### *3.3.4* Indexing in pandas

Pandas indexing works in one of two paradigms. The first is **index-based selection**: selecting data based on its numerical position in the data. `iloc` follows this paradigm.

To select the first row of data in a DataFrame, we may use the following:

In [ ]:
df_bobAndSueAndBot.iloc[0]

Bob     I liked it.
Sue    Pretty good.
Name: 0, dtype: object

Both `loc` and `iloc` are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns. To get a column with `iloc`, we can do the following:

In [ ]:
df_bobAndSueAndBot.iloc[:, 0]

0      I liked it.
1    It was awful.
Name: Bob, dtype: object

It's also possible to pass a list:

In [ ]:
df_bobAndSueAndBot.iloc[[1], 0]

1    It was awful.
Name: Bob, dtype: object

### *3.3.5* Label-based selection

The second paradigm for attribute selection is the one followed by the `loc` operator: **label-based selection**. In this paradigm, it's the data index value, not its position, which matters.

For example, to get the first entry in `df_bobAndSueAndBot`, we would now do the following:

In [ ]:
df_bobAndSueAndBot.loc[0, 'Sue']

'Pretty good.'

`iloc` is conceptually simpler than `loc` because it ignores the dataset's indices. When we use `iloc` we treat the dataset like a big matrix (a list of lists), one that we have to index into by position. `loc`, by contrast, uses the information in the indices to do its work. Since your dataset usually has meaningful indices, it's usually easier to do things using loc instead. For example, here's one operation that's much easier using `loc`:

In [ ]:
df_bobAndSueAndBot.loc[0, ["Sue","Bob"]]

Sue    Pretty good.
Bob     I liked it.
Name: 0, dtype: object

**Choosing between `loc` and `iloc`**

When choosing or transitioning between `loc` and `iloc`, there is one "gotcha" worth keeping in mind, which is that the two methods use slightly different indexing schemes.

`iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded. So 0:10 will select entries 0,...,9. `loc`, meanwhile, indexes inclusively. So 0:10 will select entries 0,...,10.

Why the change? Remember that `loc` can index any stdlib type: `strings`, for example. If we have a DataFrame with index values Apples, ..., Potatoes, ..., and we want to select "all the alphabetical fruit choices between Apples and Potatoes", then it's a lot more convenient to index df.loc['Apples':'Potatoes'] than it is to index something like df.loc['Apples', 'Potatoet'] (t coming after s in the alphabet).

This is particularly confusing when the DataFrame index is a simple numerical list, e.g. 0,...,1000. In this case df.iloc[0:1000] will return 1000 entries, while df.loc[0:1000] return 1001 of them! To get 1000 elements using loc, you will need to go one lower and ask for df.loc[0:999].

Otherwise, the semantics of using `loc` are the same as those for `iloc`.


### *3.3.6* Conditional selection

So far we've been indexing various strides of data, using structural properties of the DataFrame itself. To do *interesting* things with the data, however, we often need to ask questions based on conditions.

For example, suppose that we're interested specifically in what Bot voted for on not.

We can start by checking the score given:

In [ ]:
df_bobAndSueAndBot.Bot > 0

0     True
1    False
2     True
Name: Bot, dtype: bool

This operation produced a `Series` of `True/False` booleans based on the note of Bot. This result can then be used inside of `loc` to select the relevant data:

In [ ]:
df_bobAndSueAndBot.loc[df_bobAndSueAndBot.Bot > 0]

Bob           Sue  Bot
0  I liked it.  Pretty good.  1.0
2          Meh      Overated  0.5

We also wanted to know which ones Bob said "I liked it.".

We can use the ampersand (&) to bring the two questions together:

In [ ]:
df_bobAndSueAndBot.loc[(df_bobAndSueAndBot.Bot > 0) & (df_bobAndSueAndBot.Bob == "I liked it.")]

Bob           Sue  Bot
0  I liked it.  Pretty good.  1.0

### *3.3.7* Pandas built-in conditional selectors

Pandas comes with a few built-in conditional selectors, two of which we will highlight here.

The first is `isin`. `isin` is lets you select data whose value "is in" a list of values. 

The second is `isnull` (and its companionq `notnull`, `isna`). These methods let you highlight values which are (or are not) empty (NaN). 

You will use them in the next notebook

### *3.3.8* Assigning data

Going the other way, assigning data to a DataFrame is easy. You can assign either a constant value:

In [ ]:
df_bobAndSueAndBot['critic'] = 'Ok'
df_bobAndSueAndBot

Bob           Sue  Bot critic  index_backwards
0    I liked it.  Pretty good.  1.0     Ok                3
1  It was awful.        Bland.  0.0     Ok                2
2            Meh      Overated  0.5     Ok                1

Or with an iterable of values:

In [ ]:
df_bobAndSueAndBot['index_backwards'] = range(len(df_bobAndSueAndBot), 0, -1)
df_bobAndSueAndBot

Bob           Sue  Bot critic  index_backwards
0    I liked it.  Pretty good.  1.0     Ok                3
1  It was awful.        Bland.  0.0     Ok                2
2            Meh      Overated  0.5     Ok                1

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=1b78842c-71a5-4e9a-96da-32020e6267af' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>